package net.sf.sail.cms.curnit;

import java.io.File;
import java.util.Date;
import java.util.List;
import java.util.zip.ZipFile;

/**
 * @author rokham
 * Definition of the Curnit object which will be passed between the CMS and the Project Layer
 *
 */
public class CurnitOtmlImpl {
	
	// Unique number defining each curnit
	private String curnitNumber;
	
	// Name given to the curnit by the author
	private String curnitName;

	// Comment added to each submitted version of the curnit 
	private String comment;
	
	// Generated by the authoring tool
	private File otmlFile;
	
	// The resources used by the otml file
	private List<File> attachments;
	
	// Curnit author's details
	//private String author;
	
	// Specific version of this copy of the curnit
	private String version;
	
	// Exact time this version of the curnit was created
	private Date timeStamp;
	
	/*
	 * The rest of the attributes associated to a Curnit object, to be defined
	 * 
	 * OTML - A file
	 * List of data referred to in the OTML file - These can be either binary data or URL to links online
	 * author - I think we should create and Author object with (name, last name, user name...etc)
	 * version - used by CMS side to let retriever of the curnit know of their version
	 * timestamp - to be generated/used on CMS end
	 * 
	 */
	
}
