package net.sf.sail.cms.curnit;

import org.apache.jackrabbit.ocm.mapper.impl.annotation.Field;
import org.apache.jackrabbit.ocm.mapper.impl.annotation.Node;

/**
 * @author rokham
 * Definition of the Curnit object which will be passed between the CMS and the Project Layer
 *
 */

@Node
public class CurnitOtmlImpl{
	
	// Unique number defining each curnit
	@Field(path=true) String name;
	
	// Name given to the curnit by the author
	@Field String title;


	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}


	// Comment added to each submitted version of the curnit 
//	private String comment;
//	
//	// Generated by the authoring tool
//	private File otmlFile;
//	
//	// The resources used by the otml file
//	private List<File> attachments;
//	
//	// Curnit author's details
//	private String author;
//	
//	// Specific version of this copy of the curnit
//	private String version;
//	
//	// Exact time this version of the curnit was created
//	private Date timeStamp;
	
	
//	public Node curnitToNode(Session session) {
//		
//		Node root;
//		try {
//			root = session.getRootNode();
//			Node curnit = root.addNode("curnit", "nt:unstructured");
//			curnit.addMixin("mix:versionable");
//			
//			// adding curnit's properties
//			curnit.setProperty("number", this.getCurnitNumber());
//			curnit.setProperty("name", this.getCurnitName());
//			curnit.setProperty("comment", this.getCurnitComment());
//			
//			// adding the otml file
//			Node otml = curnit.addNode("otml", "nt:file");
//			Node content = otml.addNode("jcr:content", "nt:resource");
//			InputStream inputStrm = new FileInputStream(this.getOtmlFile());
//			content.setProperty("jcr:data", inputStrm);
//			
//			// adding the attachments
//			Node attachments = curnit.addNode("attachments", "nt:folder");
//			Node attachment = null;
//			for (File file: this.getAttachments()){
//				attachment = attachments.addNode(file.getName(), "nt:file");
//				content = attachment.addNode("jcr:content", "nt:resource");
//				inputStrm = new FileInputStream(file);
//				content.setProperty("jcr:data", inputStrm);
//			}
//			
//			return curnit;
//			
//		} catch (RepositoryException e) {
//			e.printStackTrace();
//		} catch (FileNotFoundException e){
//			e.printStackTrace();
//		}
//		return null;
//	}


	public String toString(){
		return "Name is:\t" + this.getName() + "\n Number is:\t" + this.getTitle();
	}


}
