
    create table roles (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        role varchar(255) not null,
        primary key (id),
        unique (role)
    )

    create table sds_curnits (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        sdsObjectId integer,
        name varchar(255),
        url varchar(255),
        primary key (id)
    )

    create table sds_jnlps (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        sdsObjectId integer,
        name varchar(255),
        url varchar(255),
        primary key (id)
    )

    create table sds_offerings (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        name varchar(255) not null,
        offering_id integer not null,
        sds_jnlp_fk bigint not null,
        sds_curnit_fk bigint not null,
        primary key (id),
        unique (offering_id)
    )

    create table sds_users (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        user_id integer not null,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        primary key (id),
        unique (user_id)
    )

    create table sds_workgroups (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        workgroup_id integer not null,
        name varchar(255) not null,
        sds_offering_fk bigint not null,
        primary key (id),
        unique (workgroup_id)
    )

    create table sds_workgroups_sds_users (
        sds_workgroup_fk bigint not null,
        sds_user_fk bigint not null,
        primary key (sds_workgroup_fk, sds_user_fk)
    )

    create table user_details (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        password varchar(255) not null,
        username varchar(255) not null,
        email_address varchar(255),
        account_not_expired bit not null,
        account_not_locked bit not null,
        credentials_not_expired bit not null,
        enabled bit not null,
        primary key (id),
        unique (username)
    )

    create table users (
        id bigint generated by default as identity (start with 1),
        OPTLOCK integer,
        sds_user_fk bigint not null,
        user_details_fk bigint not null,
        primary key (id),
        unique (sds_user_fk),
        unique (user_details_fk)
    )

    create table users_roles (
        user_fk bigint not null,
        role_fk bigint not null,
        primary key (user_fk, role_fk)
    )

    alter table sds_offerings 
        add constraint FK242EBD70A532A941 
        foreign key (sds_jnlp_fk) 
        references sds_jnlps

    alter table sds_offerings 
        add constraint FK242EBD701B78E061 
        foreign key (sds_curnit_fk) 
        references sds_curnits

    alter table sds_workgroups 
        add constraint FK440A0C42AB4F6201 
        foreign key (sds_offering_fk) 
        references sds_offerings

    alter table sds_workgroups_sds_users 
        add constraint FK9D05100E5AAC23E7 
        foreign key (sds_workgroup_fk) 
        references sds_workgroups

    alter table sds_workgroups_sds_users 
        add constraint FK9D05100EF342C661 
        foreign key (sds_user_fk) 
        references sds_users

    alter table users 
        add constraint FK6A68E08E3B038C2 
        foreign key (user_details_fk) 
        references user_details

    alter table users 
        add constraint FK6A68E08F342C661 
        foreign key (sds_user_fk) 
        references sds_users

    alter table users_roles 
        add constraint FKF6CCD9C6C90D39A5 
        foreign key (user_fk) 
        references user_details

    alter table users_roles 
        add constraint FKF6CCD9C68DCB6121 
        foreign key (role_fk) 
        references roles
